trigger:
- master

pool: Default

steps:
- script: terraform init
  displayName: 'terraform init'
  env:
    ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

- script: terraform plan -out vm.tfplan
  displayName: 'terraform plan -var="resource-group-name=$(RESOURCE_GROUP_NAME)"'

- script: terraform apply vm.tfplan
  displayName: 'terraform apply -var="resource-group-name=$(RESOURCE_GROUP_NAME)" -auto-approve'
