trigger:
- master

pool: Default

steps:
- script: terraform init
  displayName: 'terraform init'
  env:
    ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

- script: terraform plan -out vm.tfplan -var="resource-group-name=$(RESOURCE_GROUP_NAME)"
  displayName: 'terraform plan'

- script: terraform apply vm.tfplan -var="resource-group-name=$(RESOURCE_GROUP_NAME)" -auto-approve
  displayName: 'terraform apply'
