# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool: Default

steps:
- script: terraform init
  displayName: 'terraform init'

- script: terraform import "azurerm_resource_group.rg-challenge-prod-1" "/subscriptions/$SUBSCRIPTION/resourceGroups/rg-challenge-prod-1"
  displayName: 'terraform import'
  env:
    SUBSCRIPTION: $(SUBSCRIPTION)

- script: terraform plan -out vm.tfplan
  displayName: 'terraform plan'

- script: terraform apply vm.tfplan
  displayName: 'terraform apply'
