parameters:
- name: group
  displayName: Resource Group
  type: string
  default: 'rg-container'

trigger:
  branches:
    include: 
    - master
  paths:
    include:
    - pipeline1/*
    - pipeline1.yml

pool: Default

steps:
- script: terraform init
  displayName: 'terraform init'
  workingDirectory: pipeline1/
  env:
    ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

- script: terraform plan -out container.tfplan -var="resource-group-name=${{ parameters.group }}"
  displayName: 'terraform plan'
  workingDirectory: pipeline1/

- script: terraform apply -auto-approve container.tfplan
  displayName: 'terraform apply'
  workingDirectory: pipeline1/
