parameters:
- name: group
  type: string
  default: 'rg-vault'

trigger:
  branches:
    include: 
    - master
  paths:
    include:
    - pipeline2/*
    - pipeline2.yml

pool: Default

steps:
- script: terraform init
  displayName: 'terraform init'
  workingDirectory: pipeline2/
  env:
    ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

- script: terraform plan -out vault.tfplan -var="resource-group-name=${{ parameters.group }}"
  displayName: 'terraform plan'
  workingDirectory: pipeline2/

- script: terraform apply -auto-approve vault.tfplan
  displayName: 'terraform apply'
  workingDirectory: pipeline2/
