trigger:
  branches:
    include: 
    - master
  paths:
    include:
    - /pipeline1/

pool: Default

steps:
- script: terraform init
  displayName: 'terraform init'
  env:
    ARM_ACCESS_KEY: $(ARM_ACCESS_KEY)

- script: terraform plan -out vm.tfplan -var="resource-group-name=$(RESOURCE_GROUP_NAME)"
  displayName: 'terraform plan'

- script: terraform apply -auto-approve vm.tfplan
  displayName: 'terraform apply'
